/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompetitionListRouteImport } from './routes/competition-list'
import { Route as AnotherDemoPageRouteImport } from './routes/another-demo-page'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as CompetitionCompetitionIdRouteImport } from './routes/competition.$competitionId'

const CompetitionListRoute = CompetitionListRouteImport.update({
  id: '/competition-list',
  path: '/competition-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotherDemoPageRoute = AnotherDemoPageRouteImport.update({
  id: '/another-demo-page',
  path: '/another-demo-page',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionCompetitionIdRoute =
  CompetitionCompetitionIdRouteImport.update({
    id: '/competition/$competitionId',
    path: '/competition/$competitionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/another-demo-page': typeof AnotherDemoPageRoute
  '/competition-list': typeof CompetitionListRoute
  '/competition/$competitionId': typeof CompetitionCompetitionIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/another-demo-page': typeof AnotherDemoPageRoute
  '/competition-list': typeof CompetitionListRoute
  '/competition/$competitionId': typeof CompetitionCompetitionIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/another-demo-page': typeof AnotherDemoPageRoute
  '/competition-list': typeof CompetitionListRoute
  '/competition/$competitionId': typeof CompetitionCompetitionIdRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/another-demo-page'
    | '/competition-list'
    | '/competition/$competitionId'
    | '/demo/tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/another-demo-page'
    | '/competition-list'
    | '/competition/$competitionId'
    | '/demo/tanstack-query'
  id:
    | '__root__'
    | '/'
    | '/another-demo-page'
    | '/competition-list'
    | '/competition/$competitionId'
    | '/demo/tanstack-query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnotherDemoPageRoute: typeof AnotherDemoPageRoute
  CompetitionListRoute: typeof CompetitionListRoute
  CompetitionCompetitionIdRoute: typeof CompetitionCompetitionIdRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/competition-list': {
      id: '/competition-list'
      path: '/competition-list'
      fullPath: '/competition-list'
      preLoaderRoute: typeof CompetitionListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/another-demo-page': {
      id: '/another-demo-page'
      path: '/another-demo-page'
      fullPath: '/another-demo-page'
      preLoaderRoute: typeof AnotherDemoPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition/$competitionId': {
      id: '/competition/$competitionId'
      path: '/competition/$competitionId'
      fullPath: '/competition/$competitionId'
      preLoaderRoute: typeof CompetitionCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnotherDemoPageRoute: AnotherDemoPageRoute,
  CompetitionListRoute: CompetitionListRoute,
  CompetitionCompetitionIdRoute: CompetitionCompetitionIdRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
